name: Check package version

run-name: ${{github.repository}} is running

on:
  pull_request:
    branches:
      - 'test'

jobs:
  check-package-version:
    if: github.repository == 'inseong01/inseong01'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest changes
        run: |
          git fetch origin

          echo "PR Branch: ${{ github.head_ref }}"  # PR을 보낸 브랜치
          echo "Base Branch: ${{ github.base_ref }}"  # 기준 브랜치

      - name: Find merge branch package.json
        run: |
          FILE_PATH=$(find . -type f -name "package.json" | head -n 1)
          COMMIT_HASH=$(git log -n 1 --pretty=format:"%H" "$FILE_PATH")

          echo "FILE_PATH: $FILE_PATH"
          echo "COMMIT_HASH: $COMMIT_HASH"
          echo "PREV_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo "Succeeded"

      - name: Find package.json in the PR branch
        run: |
          # PR에서 변경된 파일을 찾기 위해 PR 브랜치에서 변경된 파일 목록을 확인
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }})
          echo "Changed files in the PR: $CHANGED_FILES"

          # package.json이 변경되었으면 파일 경로 추출
          if echo "$CHANGED_FILES" | grep -q "package.json"; then
            FILE_PATH="package.json"
            echo "package.json file has been modified in the PR"
          else
            echo "Error: package.json not found in the PR changes"
            exit 1
          fi

          echo "CUR_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo "FILE_PATH: $FILE_PATH"
          echo "Succeeded"

      - name: Compare package.json version
        run: |
          CUR_VERSION=$(jq -r '.version' $CUR_PACKAGE_JSON_PATH)
          PREV_VERSION=$(jq -r '.version' $PREV_PACKAGE_JSON_PATH)

          echo "CUR_VERSION: $CUR_VERSION"
          echo "PREV_VERSION: $PREV_VERSION"

          if  [[ "$(printf '%s\n%s' "$PREV_VERSION" "$CUR_VERSION" | sort -V | head -n 1 )" == "$CUR_VERSION" ]]; then
            echo "Error: Check current package.json version"
            echo "Current version is not greater than previous version"
            exit 1
          fi

          echo "Succeeded"
