name: Check package version

run-name: ${{github.repository}} is running

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - 'test2'

jobs:
  get-current-file:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Get file in Head branch
        run: |
          FILE_PATH=$(find . -type f -name "package.json")
          COMMIT_HASH=$(git log -n 1 --pretty=format:%H -- "$FILE_PATH")

          echo "FILE_PATH: $FILE_PATH"
          echo "FILE_PATH HASH: $COMMIT_HASH"
          echo "HEAD_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo "Succeeded"

  check-package-version:
    if: github.repository == 'inseong01/inseong01'
    runs-on: ubuntu-latest
    needs: get-current-file

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Checkout Base
        env:
          BASE_REF: ${{ github.base_ref }} # 기준 브랜치
        run: |
          echo "BASE_REF: $BASE_REF"
          git fetch origin "$BASE_REF"
          git checkout "$BASE_REF"

      - name: Get file in Base branch
        run: |
          FILE_PATH=$(find . -type f -name "package.json" | head -n 1)
          COMMIT_HASH=$(git log -n 1 --pretty=format:%H -- "$FILE_PATH")

          echo "FILE_PATH: $FILE_PATH"
          echo "FILE_PATH HASH: $COMMIT_HASH"
          echo "BASE_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV

      - name: Compare file version
        run: |
          PREV_VERSION=$(jq -r '.version' $BASE_PACKAGE_JSON_PATH)
          CUR_VERSION=$(jq -r '.version' $HEAD_PACKAGE_JSON_PATH)

          echo "CUR_VERSION: $CUR_VERSION"
          echo "PREV_VERSION: $PREV_VERSION"

          if [[ "$CUR_VERSION" == "$PREV_VERSION" ]]; then
            echo "Error: Current package.json version is the same as the previous version."
            exit 1
          fi

          if  [[ "$(printf '%s\n%s' "$PREV_VERSION" "$CUR_VERSION" | sort -V | head -n 1 )" == "$CUR_VERSION" ]]; then
            echo "Error: Check current package.json version"
            echo "Current version is not greater than previous version"
            exit 1
          fi

          echo "Succeeded"
