name: Check work log

run-name: ${{github.repository}} is running

on:
  pull_request:
    branches:
      - 'test'

jobs:
  check-package-version:
    if: github.repository == 'inseong01/inseong01'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find package.json
        run: |
          FILE_PATH=$(find . -type f -name "package.json" | head -n 1)
          COMMIT_HASH=$(git log -n 1 --pretty=format:"%H" "$FILE_PATH")

          echo "FILE_PATH: $FILE_PATH"
          echo "COMMIT_HASH: $COMMIT_HASH"

          if [ ! -f "$FILE_PATH" ]; then
            echo "Error: FILE_PATH was not found"
            exit 1
          fi

          echo "CUR_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo "Succeeded"

      - name: Checkout previous package.json
        run: |
          git checkout HEAD~1 -- $(find . -type f -name "package.json" | head -n 1)

      - name: Find package.json
        run: |
          FILE_PATH=$(find . -type f -name "package.json" | head -n 1)
          COMMIT_HASH=$(git log -n 1 --pretty=format:"%H" "$FILE_PATH")

          echo "FILE_PATH: $FILE_PATH"
          echo "COMMIT_HASH: $COMMIT_HASH"

          if [ ! -f "$FILE_PATH" ]; then
            echo "Error: FILE_PATH was not found"
            exit 1
          fi

          git restore .

          echo "PREV_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo "Succeeded"

      - name: Compare package.json version
        run: |
          CUR_VERSION=$(jq -r '.version' $CUR_PACKAGE_JSON_PATH)
          PREV_VERSION=$(jq -r '.version' $PREV_PACKAGE_JSON_PATH)

          echo "CUR_VERSION: $CUR_VERSION"
          echo "PREV_VERSION: $PREV_VERSION"

          if  [[ "$(printf '%s\n%s' "$PREV_VERSION" "$CUR_VERSION" | sort -V | head -n 1 )" == "$CUR_VERSION" ]]; then
            echo "Error: Check current package.json version"
            echo "Current version is not greater than previous version"
            exit 1
          fi

          echo "Succeeded"
