name: Check package version

run-name: ${{github.repository}} is running

on:
  pull_request:
    branches:
      - 'test'

jobs:
  check-package-version:
    if: github.repository == 'inseong01/inseong01'
    runs-on: ubuntu-latest

    steps:
      - name: Use actions/checkout@v3
        uses: actions/checkout@v3

      - name: Fetch latest changes
        run: |
          git fetch origin

          echo "PR Branch: ${{ github.head_ref }}"  # PR 브랜치
          echo "Base Branch: ${{ github.base_ref }}"  # 기준 브랜치

      - name: Find package.json in current branch
        run: |
          FILE_PATH=$(find . -type f -name "package.json" | head -n 1)
          COMMIT_HASH=$(git log -n 1 --pretty=format:"%H" "$FILE_PATH")

          echo "FILE_PATH: $FILE_PATH"
          echo "COMMIT_HASH: $COMMIT_HASH"
          echo "CURRENT_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo "Succeeded"

      - name: Checkout test repository
        run: |
          git checkout test

      - name: Find package.json in the merge branch
        run: |
          FILE_PATH=$(find . -type f -name "package.json" | head -n 1)

          echo "PREV_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo "FILE_PATH: $FILE_PATH"
          echo "Succeeded"

      - name: Compare package.json version
        run: |
          CUR_VERSION=$(jq -r '.version' $PREV_PACKAGE_JSON_PATH)
          PREV_VERSION=$(jq -r '.version' $CURRENT_PACKAGE_JSON_PATH)

          echo "CUR_VERSION: $CUR_VERSION"
          echo "PREV_VERSION: $PREV_VERSION"

          if  [[ "$(printf '%s\n%s' "$PREV_VERSION" "$CUR_VERSION" | sort -V | head -n 1 )" == "$CUR_VERSION" ]]; then
            echo "Error: Check current package.json version"
            echo "Current version is not greater than previous version"
            exit 1
          fi

          echo "Succeeded"
