name: Check package version

run-name: ${{github.repository}} is running

on:
  pull_request:
    branches:
      - 'test'

jobs:
  check-package-version:
    if: github.repository == 'inseong01/inseong01'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Head
        uses: actions/checkout@v3

      - name: Get package.json file in Head branch
        env:
          GH_TOKEN: ${{ github.token }}
          HEAD_SHA: ${{ github.head_ref }} # PR 브랜치
          BASE_SHA: ${{ github.base_ref }} # 기준 브랜치
        run: |
          # FILE_PATH=$(find . -type f -name "package.json" | head -n 1)
          FILE_PATHS=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep "package.json$" || echo "")

          # filter out files that are not markdown
          FILE_PATH=$(echo "${FILE_PATH}" | egrep -i "package.json$" | xargs)

          echo "FILE_PATH: $FILE_PATH"
          echo "CURRENT_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo "Succeeded"

      - name: Checkout Base
        run: |
          git checkout $BASE_SHA

      - name: Get package.json file in the Base branch
        run: |
          FILE_PATH=$(find . -type f -name "package.json" | head -n 1)

          echo "FILE_PATH: $FILE_PATH"
          echo "PREV_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo "Succeeded"

      - name: Compare package.json version
        run: |
          CUR_VERSION=$(jq -r '.version' $PREV_PACKAGE_JSON_PATH)
          PREV_VERSION=$(jq -r '.version' $CURRENT_PACKAGE_JSON_PATH)

          echo "CUR_VERSION: $CUR_VERSION"
          echo "PREV_VERSION: $PREV_VERSION"

          if  [[ "$(printf '%s\n%s' "$PREV_VERSION" "$CUR_VERSION" | sort -V | head -n 1 )" == "$CUR_VERSION" ]]; then
            echo "Error: Check current package.json version"
            echo "Current version is not greater than previous version"
            exit 1
          fi

          echo "Succeeded"
