name: Check package version

run-name: ${{github.repository}} is running

on:
  pull_request:
    branches:
      - 'test2'

jobs:
  check-package-version:
    if: github.repository == 'inseong01/inseong01'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Head
        uses: actions/checkout@v3

      - name: Get file in Head branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          FILE_PATH=$(find . -type f -name "package.json" | head -n 1)

          if [ -z "$FILE_PATH" ]; then
            echo "File doesn't exist"
            exit 1
          fi

          echo "Current Branch: ${{ github.ref_name }}"
          echo "FILE_PATH: $FILE_PATH"
          echo "HEAD_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo "Succeeded"

      - name: Checkout Base
        env:
          BASE_REF: ${{ github.base_ref }} # 기준 브랜치
        run: |
          echo "BASE_REF: $BASE_REF"

          git fetch origin "$BASE_REF" --depth=1
          git show "$BASE_REF":package.json > package.base.json

          echo "Current Branch: ${{ github.ref_name }}"
          echo "BASE_PACKAGE_JSON_PATH=package.base.json" >> $GITHUB_ENV

      - name: Compare file version
        run: |
          CUR_VERSION=$(jq -r '.version' $BASE_PACKAGE_JSON_PATH)
          PREV_VERSION=$(jq -r '.version' $HEAD_PACKAGE_JSON_PATH)

          echo "CUR_VERSION: $CUR_VERSION"
          echo "PREV_VERSION: $PREV_VERSION"

          if  [[ "$(printf '%s\n%s' "$PREV_VERSION" "$CUR_VERSION" | sort -V | head -n 1 )" == "$CUR_VERSION" ]]; then
            echo "Error: Check current package.json version"
            echo "Current version is not greater than previous version"
            exit 1
          fi

          echo "Succeeded"
