name: Check work log

run-name: ${{github.repository}} is running

on:
  # workflow_dispatch:

  push:
    branches:
      - '**' # 모든 브랜치 적용
    #paths:
    # - '**/*.md'

jobs:
  check-work-log-file:
    if: github.repository == 'inseong01/inseong01'
    runs-on: ubuntu-latest

    steps:
      - name: Get current date 1
        id: t1
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: 'YYYY.MM.DD.'
          timezone-offset: -540

      - name: Output 1
        run: |
          echo "The time was ${{ steps.t1.outputs.time }}"
          echo "The year was ${{ steps.t1.outputs.year }}"
          echo "The month was ${{ steps.t1.outputs.month }}"
          echo "The day was ${{ steps.t1.outputs.day }}"

      - name: Get current date 2
        id: t2
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: 'YYYY.MM.DD.'
          timezone-offset: -540

      - name: Output 2
        run: |
          YEAR_SHORT=$(echo "${{ steps.t2.outputs.year }}" | cut -c3-4)
          MONTH=$(expr ${{ steps.t2.outputs.month }} + 0)
          DAY=$(expr ${{ steps.t2.outputs.day }} + 0)

          echo "The time was ${{ steps.t2.outputs.time }}" 
          echo "The year was $YEAR_SHORT"
          echo "The month was $MONTH"
          echo "The day was $DAY"
